Add writer endpoints
ZZireal/koa-api-starter pull request #1
Opened 2020-07-30 08:27 UTC by ZZireal

2020-08-03 12:52 UTC, paralectvkomodey requested changes

2020-08-03 12:52 UTC, paralectvkomodey commented on src/resources/writer/add-writer-book/index.js
> +    console.log(data);
Не стоит оставлять инструкции для дебага в продакшне. Они засоряют общий лог

2020-08-03 12:52 UTC, paralectvkomodey commented on src/resources/writer/add-writer-book/index.js
> +    doc.books.push(data);
1. В MongoDB есть оператор $push, лучше использовать его нежели js
2. Так как есть $push, то лучше юзать атомарный аналог update

2020-08-03 12:52 UTC, paralectvkomodey commented on src/resources/writer/create-writer-and-books/index.js
> +  console.log(firstName, lastName);
То же самое как и с предыдущим console.log

2020-08-03 12:52 UTC, paralectvkomodey commented on src/resources/writer/create-writer-and-books/index.js
> +  console.log(data);
again

2020-08-03 12:52 UTC, paralectvkomodey commented on src/resources/writer/create-writer-and-books/index.js
> +    books: data.books,
Каким образом регулируется уникальность `_id` в writer и books?
Отдавать такую ответственность клиенту - плохая практика, потому что клиентов много, а id должен быть уникальным по всей коллекции

Лучше использовать
а) ObjectID из MongoDB
б) Либо специализированные библиотеки типа shortid, GUID, UID

2020-08-03 12:52 UTC, paralectvkomodey commented on src/resources/writer/delete-writer-book/index.js
> +  console.log("sdfdsfsdf");
хым

2020-08-03 12:52 UTC, paralectvkomodey commented on src/resources/writer/delete-writer-book/index.js
> +      !(book._id === +ctx.params.bookId)
`!==` ?:)

2020-08-03 12:52 UTC, paralectvkomodey commented on src/resources/writer/update-writer-books/index.js
> +    doc.books = ctx.request.body.books;
Кажется, что здесь можно обойтись атомарным методом update + `$set` инструкцией напрямую в mongodb

2020-08-03 12:52 UTC, paralectvkomodey commented on src/resources/writer/update-writer/index.js
> +        _global: ['This writer is not exists'],
DRY:

У тебя очень много мест, в которых используется одна и та же конструкция ошибки в респонсе. В случае, когда ты захочешь поменять эту схему - тебе придется найти ВСЕ места в которых вызывается ошибка и поменять их. Такой подход очень error prone. Если хочешь кидать одну ошибку - инкапсулируй логику в одном месте и импортируй

2020-08-03 12:52 UTC, paralectvkomodey commented on src/resources/writer/update-writer/index.js
> +    if (data.age) doc.age = data.age;
Лучше использовать оператор $set и атомарный update

2020-08-03 12:52 UTC, paralectvkomodey commented on src/resources/writer/writer.schema.js
> +      _id: Joi.string().required(),
Странно, что у тебя везде _id number, а тут string

2020-08-06 13:45 UTC, paralectvkomodey requested changes

2020-08-06 13:45 UTC, paralectvkomodey commented on package.json
> +    "shortid": "2.2.15",
А зачем в коде 3 библиотеки shortid?

2020-08-07 06:29 UTC, ZZireal commented on package.json
> +    "shortid": "2.2.15",
у меня не получалось запустить проект, писало, что библиотека не установлена, и я начала гуглить и устаналивать все shortid, что находила, т.к. думала, что с теми библиотеками что-то не так)0) потом оказалось, что проблема в другом (вроде надо было сбилдить проект заново)

2020-08-07 07:12 UTC, paralectvkomodey approved these changes

2020-08-07 07:13 UTC, merged